In [ ]:
import zipfile
with zipfile.ZipFile("/content/t20s.zip","r") as zip_ref:
    zip_ref.extractall("/content/drive/MyDrive/T20")

In [ ]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [ ]:
filenames = []
for file in os.listdir('/content/drive/MyDrive/T20 world cup cricket score analysis/data'):
    filenames.append(os.path.join('/content/drive/MyDrive/T20',file))

In [ ]:
filenames[0:5]

['/content/drive/MyDrive/T20/1185154.yaml',
 '/content/drive/MyDrive/T20/1185155.yaml',
 '/content/drive/MyDrive/T20/1185186.yaml',
 '/content/drive/MyDrive/T20/1185182.yaml',
 '/content/drive/MyDrive/T20/1185181.yaml']

In [ ]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = final_df.append(df)
        counter+=1
        
final_df

 69%|██████▉   | 995/1435 [05:41<02:48,  2.61it/s]

In [ ]:
backup = final_df.copy()

In [ ]:
backup = final_df.copy()

In [ ]:
final_df

In [ ]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [ ]:
final_df

                                              innings  ... info.player_of_match
0   [{'1st innings': {'team': 'West Indies', 'deli...  ...                  NaN
0   [{'1st innings': {'team': 'West Indies', 'deli...  ...                  NaN
0   [{'1st innings': {'team': 'West Indies', 'deli...  ...                  NaN
0   [{'1st innings': {'team': 'Guernsey', 'deliver...  ...                  NaN
0   [{'1st innings': {'team': 'Denmark', 'deliveri...  ...           [SA Ahmad]
..                                                ...  ...                  ...
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [Umar Akmal]
0   [{'1st innings': {'team': 'Bangladesh', 'deliv...  ...           [S Dhawan]
0   [{'1st innings': {'team': 'Netherlands', 'deli...  ...   [Mudassar Bukhari]
0   [{'1st innings': {'team': 'Australia', 'delive...  ...         [GJ Maxwell]
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [GJ Maxwell]

[998 rows x 14 columns]

In [ ]:
final_df['info.gender'].value_counts()

male      760
female    238
Name: info.gender, dtype: int64

In [ ]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                                              innings  ... info.player_of_match
0   [{'1st innings': {'team': 'Guernsey', 'deliver...  ...                  NaN
0   [{'1st innings': {'team': 'Denmark', 'deliveri...  ...           [SA Ahmad]
0   [{'1st innings': {'team': 'Jersey', 'deliverie...  ...                  NaN
0   [{'1st innings': {'team': 'Italy', 'deliveries...  ...                  NaN
0   [{'1st innings': {'team': 'Jersey', 'deliverie...  ...        [BDH Stevens]
..                                                ...  ...                  ...
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [Umar Akmal]
0   [{'1st innings': {'team': 'Bangladesh', 'deliv...  ...           [S Dhawan]
0   [{'1st innings': {'team': 'Netherlands', 'deli...  ...   [Mudassar Bukhari]
0   [{'1st innings': {'team': 'Australia', 'delive...  ...         [GJ Maxwell]
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [GJ Maxwell]

[760 rows x 13 columns]

In [ ]:
final_df['info.match_type'].value_counts()

T20    760
Name: info.match_type, dtype: int64

In [ ]:
final_df['info.overs'].value_counts()

20    757
50      3
Name: info.overs, dtype: int64

In [ ]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                                              innings  ... info.player_of_match
0   [{'1st innings': {'team': 'Guernsey', 'deliver...  ...                  NaN
0   [{'1st innings': {'team': 'Denmark', 'deliveri...  ...           [SA Ahmad]
0   [{'1st innings': {'team': 'Jersey', 'deliverie...  ...                  NaN
0   [{'1st innings': {'team': 'Italy', 'deliveries...  ...                  NaN
0   [{'1st innings': {'team': 'Jersey', 'deliverie...  ...        [BDH Stevens]
..                                                ...  ...                  ...
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [Umar Akmal]
0   [{'1st innings': {'team': 'Bangladesh', 'deliv...  ...           [S Dhawan]
0   [{'1st innings': {'team': 'Netherlands', 'deli...  ...   [Mudassar Bukhari]
0   [{'1st innings': {'team': 'Australia', 'delive...  ...         [GJ Maxwell]
0   [{'1st innings': {'team': 'Sri Lanka', 'delive...  ...         [GJ Maxwell]

[757 rows x 11 columns]

In [ ]:
cd ..

/content/drive/My Drive

In [ ]:
import pickle
#pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [ ]:
matches = pickle.load(open('dataset_level1.pkl','rb'))
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.2: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.4: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.5: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.1: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.3: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.4: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.5: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'extras': {'wides': 1},
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {1.6: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.7: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.1: {'batsman': 'MWR Stokes',
   'bowler': 'Izatullah Dawlatzai',
   'extras': {'legbyes': 1},
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {2.2: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.3: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {2.4: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.5: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.6: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'extras': {'noballs': 1},
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {2.7: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'extras': {'wides': 1},
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {2.8: {'batsman': 'AS Wright',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {3.1: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.3: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.4: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.5: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.6: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.1: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.2: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.3: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.4: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {4.5: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {4.6: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.1: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.2: {'batsman': 'MWR Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.3: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.6: {'batsman': 'AS Wright',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {6.1: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {6.2: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.3: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.4: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'MWR Stokes',
   'bowler': 'CAJ Meschede',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': 'AS Wright',
   'bowler': 'CAJ Meschede',
   'extras': {'byes': 1},
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {7.1: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {7.2: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'MWR Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'MWR Stokes',
   'bowler': 'Muslim Yar',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.4: {'batsman': 'MWR Stokes',
   'bowler': 'Muslim Yar',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['D Weston'],
    'kind': 'caught',
    'player_out': 'MWR Stokes'}}},
 {7.5: {'batsman': 'J Butler',
   'bowler': 'Muslim Yar',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.6: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.1: {'batsman': 'J Butler',
   'bowler': 'Asad Mohammad',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.2: {'batsman': 'J Butler',
   'bowler': 'Asad Mohammad',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.3: {'batsman': 'AS Wright',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'J Butler',
   'bowler': 'Asad Mohammad',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.5: {'batsman': 'AS Wright',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': 'AS Wright',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'J Butler',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.2: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'J Butler',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.3: {'batsman': 'J Butler',
   'bowler': 'Muslim Yar',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {9.4: {'batsman': 'J Butler',
   'bowler': 'Muslim Yar',
   'non_striker': 'AS Wright',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.5: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'J Butler',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.6: {'batsman': 'AS Wright',
   'bowler': 'Muslim Yar',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['CAJ Meschede'],
    'kind': 'caught',
    'player_out': 'AS Wright'}}},
 {10.1: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.3: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.4: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.5: {'batsman': 'J Butler',
   'bowler': 'Asad Mohammad',
   'non_striker': 'DR Hooper',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.6: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.1: {'batsman': 'J Butler',
   'bowler': 'V Ganesan',
   'non_striker': 'DR Hooper',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.2: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.3: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'J Butler',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.4: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'J Butler',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.5: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'J Butler',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.6: {'batsman': 'J Butler',
   'bowler': 'V Ganesan',
   'non_striker': 'DR Hooper',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['D Weston'],
    'kind': 'stumped',
    'player_out': 'J Butler'}}},
 {12.1: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.2: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {12.3: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.4: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.5: {'batsman': 'DR Hooper',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.6: {'batsman': 'LJ Barker',
   'bowler': 'Asad Mohammad',
   'non_striker': 'DR Hooper',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.1: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.2: {'batsman': 'DR Hooper',
   'bowler': 'V Ganesan',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.3: {'batsman': 'LJ Barker',
   'bowler': 'V Ganesan',
   'non_striker': 'DR Hooper',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'run out', 'player_out': 'DR Hooper'}}},
 {13.4: {'batsman': 'LJ Barker',
   'bowler': 'V Ganesan',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.5: {'batsman': 'LJ Barker',
   'bowler': 'V Ganesan',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'LB Ferbrache',
   'bowler': 'V Ganesan',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.1: {'batsman': 'LJ Barker',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.2: {'batsman': 'LJ Barker',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.3: {'batsman': 'LB Ferbrache',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.4: {'batsman': 'LJ Barker',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.5: {'batsman': 'LB Ferbrache',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.6: {'batsman': 'LJ Barker',
   'bowler': 'Asad Mohammad',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.1: {'batsman': 'LB Ferbrache',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.2: {'batsman': 'LJ Barker',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.3: {'batsman': 'LB Ferbrache',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.4: {'batsman': 'LB Ferbrache',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.5: {'batsman': 'LJ Barker',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.6: {'batsman': 'LJ Barker',
   'bowler': 'CAJ Meschede',
   'non_striker': 'LB Ferbrache',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.1: {'batsman': 'LB Ferbrache',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['D Weston'],
    'kind': 'caught',
    'player_out': 'LB Ferbrache'}}},
 {16.2: {'batsman': 'TCR Kimber',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.3: {'batsman': 'TCR Kimber',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.4: {'batsman': 'LJ Barker',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.5: {'batsman': 'LJ Barker',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.6: {'batsman': 'LJ Barker',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'LJ Barker',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.2: {'batsman': 'TCR Kimber',
   'bowler': 'Ahmed Wardak',
   'extras': {'legbyes': 1},
   'non_striker': 'LJ Barker',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.3: {'batsman': 'LJ Barker',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Asad Mohammad'],
    'kind': 'caught',
    'player_out': 'LJ Barker'}}},
 {17.4: {'batsman': 'TCR Kimber',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'LC Le Tissier',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.5: {'batsman': 'LC Le Tissier',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCR Kimber',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.6: {'batsman': 'TCR Kimber',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'LC Le Tissier',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['D Weston'],
    'kind': 'caught',
    'player_out': 'TCR Kimber'}}},
 {18.1: {'batsman': 'LC Le Tissier',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.2: {'batsman': 'LC Le Tissier',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.3: {'batsman': 'ACF Stokes',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'LC Le Tissier',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'run out', 'player_out': 'LC Le Tissier'}}},
 {18.4: {'batsman': 'TCW Veillard',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.5: {'batsman': 'TCW Veillard',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.6: {'batsman': 'TCW Veillard',
   'bowler': 'Izatullah Dawlatzai',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'TCW Veillard',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'ACF Stokes',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.2: {'batsman': 'ACF Stokes',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCW Veillard',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['V Ganesan'],
    'kind': 'caught',
    'player_out': 'ACF Stokes'}}},
 {19.3: {'batsman': 'W Peatfield',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCW Veillard',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.4: {'batsman': 'TCW Veillard',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'W Peatfield',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.5: {'batsman': 'W Peatfield',
   'bowler': 'Ahmed Wardak',
   'non_striker': 'TCW Veillard',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'W Peatfield'}}}]

In [ ]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = delivery_df.append(loop_df)

In [ ]:
delivery_df

     match_id                   teams  ...     city                        venue
0           2     [Guernsey, Germany]  ...   Castel  King George V Sports Ground
1           2     [Guernsey, Germany]  ...   Castel  King George V Sports Ground
2           2     [Guernsey, Germany]  ...   Castel  King George V Sports Ground
3           2     [Guernsey, Germany]  ...   Castel  King George V Sports Ground
4           2     [Guernsey, Germany]  ...   Castel  King George V Sports Ground
..        ...                     ...  ...      ...                          ...
121       758  [Sri Lanka, Australia]  ...  Colombo          R Premadasa Stadium
122       758  [Sri Lanka, Australia]  ...  Colombo          R Premadasa Stadium
123       758  [Sri Lanka, Australia]  ...  Colombo          R Premadasa Stadium
124       758  [Sri Lanka, Australia]  ...  Colombo          R Premadasa Stadium
125       758  [Sri Lanka, Australia]  ...  Colombo          R Premadasa Stadium

[90627 rows x 10 columns]

In [ ]:
def bowl(row):
  for team in row['teams']:
    if team !=row['batting_team']:
      return team

In [ ]:
delivery_df['bowling_team']=delivery_df.apply(bowl,axis=1)

In [ ]:
delivery_df.drop(columns=['teams'],inplace=True)

In [ ]:
delivery_df

     match_id batting_team  ...                        venue bowling_team
0           2     Guernsey  ...  King George V Sports Ground      Germany
1           2     Guernsey  ...  King George V Sports Ground      Germany
2           2     Guernsey  ...  King George V Sports Ground      Germany
3           2     Guernsey  ...  King George V Sports Ground      Germany
4           2     Guernsey  ...  King George V Sports Ground      Germany
..        ...          ...  ...                          ...          ...
121       758    Sri Lanka  ...          R Premadasa Stadium    Australia
122       758    Sri Lanka  ...          R Premadasa Stadium    Australia
123       758    Sri Lanka  ...          R Premadasa Stadium    Australia
124       758    Sri Lanka  ...          R Premadasa Stadium    Australia
125       758    Sri Lanka  ...          R Premadasa Stadium    Australia

[90627 rows x 10 columns]

In [ ]:
delivery_df['batting_team'].unique()

array(['Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway', 'South Africa',
       'England', 'Australia', 'Thailand', 'Malaysia', 'Maldives',
       'India', 'Bangladesh', 'West Indies', 'New Zealand', 'Netherlands',
       'Singapore', 'Nepal', 'Kuwait', 'Sri Lanka', 'Afghanistan',
       'Zimbabwe', 'Bermuda', 'Canada', 'Cayman Islands',
       'United States of America', 'Namibia', 'Botswana', 'Oman',
       'Hong Kong', 'Ireland', 'Pakistan', 'United Arab Emirates',
       'Scotland', 'Papua New Guinea', 'Kenya', 'Nigeria', 'Portugal',
       'Gibraltar', 'Spain', 'Vanuatu', 'Germany', 'Bhutan', 'Qatar',
       'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania'],
      dtype=object)

In [ ]:
teams=[
       'Australia',
       'India',
       'Bangladesh',
       'New Zealand',
       'South Africa',
       'England',
       'West Indies',
       'Sri Lanka', 
       'Afghanistan',
       'Pakistan'
]

In [ ]:
delivery_df=delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df=delivery_df[delivery_df['bowling_team'].isin(teams)]

In [ ]:
output=delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [ ]:
output

     match_id  batting_team  ...         city                venue
0          13  South Africa  ...  East London         Buffalo Park
1          13  South Africa  ...  East London         Buffalo Park
2          13  South Africa  ...  East London         Buffalo Park
3          13  South Africa  ...  East London         Buffalo Park
4          13  South Africa  ...  East London         Buffalo Park
..        ...           ...  ...          ...                  ...
121       758     Sri Lanka  ...      Colombo  R Premadasa Stadium
122       758     Sri Lanka  ...      Colombo  R Premadasa Stadium
123       758     Sri Lanka  ...      Colombo  R Premadasa Stadium
124       758     Sri Lanka  ...      Colombo  R Premadasa Stadium
125       758     Sri Lanka  ...      Colombo  R Premadasa Stadium

[49263 rows x 8 columns]

In [ ]:
pickle.dump(output,open('dataset_level2.pkl','wb'))